part-up/part-up

app/packages/partup:lib/collections/users.js
=> fix(tribe-uppers): only show activate uppers on the tribe uppers overview

app/packages/partup:lib/routes.js
=> fix(verify-email): fix empty page when clicking the URL

app/packages/partup:client-base/client/uploader.js
=> fix(message): fix safari file upload

License supplement
Added a supplement to the license covering:
- trademark protection
- connecting user profiles
=> feat(license): add license supplement

.dockerignore, .gitignore, Dockerfile, docker-compose.yml, imagemagick-policy.xml
Fixes the vulnerabilty in imagemagick that's described at imagetragick.com
=> fix(imagemagick): added policy.xml to fix imagetragick vulnerability

app/packages/partup:server/collection_hooks.js
this allows @wouterd to add networks/tribes in recommender api
=> fix(events): fire events to API when CRUD'ding network object

app/packages/partup:client-header/templates/personal.html, app/packages/partup:client-header/templates/personal.js, app/packages/partup:lib/package.js, app/packages/partup:lib/routes.js
=> feat(personal-header): part-up-for-organisations in header only when user is on HomePage

app/i18n/phraseapp.en.i18n.json, app/i18n/phraseapp.nl.i18n.json, app/packages/partup:client-pages/app/discover/partials/discover-page.html, app/packages/partup:client-pages/app/discover/partials/discover-page.js
=> (client)discover page: remove invitation sentence

app/client/stylesheets/components/pu-notification.sass
hi @tlimpanont, fixed it before for your release tonight
=> fix(chatdropdown): truncate long tribe chat lines, fixing #517

app/packages/partup-client-dropdowns/menu/menu.html
=> feat(menu.html): some links open target blank and re-order

app/packages/partup-client-pages/app/profile/tabs/about.js, app/packages/partup-server/fixtures/tiles.js, app/packages/partup-server/package.js
=> Fix profile about

app/packages/partup-lib/collections/chats.js, app/packages/partup-lib/collections/networks.js, app/packages/partup-server/publications/chats.js, app/packages/partup-server/publications/users.js, app/packages/partup-server/routes/composite.js, app/packages/partup-server/services/pushnotifications_service.js
- enable notification sounds in iOS and Android
- remove archived tribes from tribes publications for chat & tribes overview
- fix sorting in part-ups endpoints
- fix tribe-chats pagination
=> Feat chat improvements for app

app/client/stylesheets/components/compositions/admin.sass, app/packages/partup-client-admin/Admin.html, app/packages/partup-client-admin/Admin.js, app/packages/partup-lib/collections/networks.js, app/packages/partup-lib/collections/users.js
=> Ft keep invite data

app/client/stylesheets/components/pu-button.sass, app/i18n/z-feat-become-partner-flow.en.i18n.json, app/i18n/z-feat-become-partner-flow.nl.i18n.json, app/packages/partup-client-dropdowns/notifications/notification/types/partup/partner-accepted.html, app/packages/partup-client-dropdowns/notifications/notification/types/partup/partner-rejected.html, app/packages/partup-client-dropdowns/notifications/notification/types/partup/partner-request.html, app/packages/partup-client-dropdowns/package.js, app/packages/partup-client-pages/app/partup/partup-sidebar.html, app/packages/partup-client-pages/app/partup/partup-sidebar.js, app/packages/partup-client-pages/app/partup/takepart/takepart.html, app/packages/partup-client-pages/app/partup/takepart/takepart.js, app/packages/partup-client-pages/modal/profile_settings/email/email.html, app/packages/partup-client-update/package.js, app/packages/partup-client-update/types/partner-request.html, app/packages/partup-client-update/types/partner-request.js, app/packages/partup-client-upper-tile/UpperTile.js, app/packages/partup-lib/collections/images.js, app/packages/partup-lib/collections/partups.js, app/packages/partup-lib/schemas/settings.js, app/packages/partup-server/accounts.js, app/packages/partup-server/compile_email_templates.js, app/packages/partup-server/event_handlers/partups/partups_uppers_handler.js, app/packages/partup-server/methods/partups/partups_methods.js, app/packages/partup-server/migrations.js, app/packages/partup-server/package.js, app/packages/partup-server/private/emails/partups_partner_request.en.html, app/packages/partup-server/private/emails/partups_partner_request.nl.html
=> Feat become partner flow

app/client/stylesheets/components/pu-button.sass, app/client/stylesheets/components/pu-dropdown.sass, app/client/stylesheets/components/pu-dropdownitem.sass, app/client/stylesheets/components/pu-page.sass, app/client/stylesheets/components/pu-profilemenu.sass, app/i18n/z-feat-new-navigation.en.i18n.json, app/i18n/z-feat-new-navigation.nl.i18n.json, app/packages/partup-client-dropdowns/menu/menu.js, app/packages/partup-client-dropdowns/package.js, app/packages/partup-client-dropdowns/profile/profile.html, app/packages/partup-client-dropdowns/profile/profile.js, app/packages/partup-client-dropdowns/tribes/tribes.html, app/packages/partup-client-dropdowns/tribes/tribes.js, app/packages/partup-client-header/templates/nav.html, app/public/images/other-partups.svg
This PR implements the new partup global navigation with the new My Tribes menu
=> Feat new navigation

app/client/stylesheets/components/pu-filterbar.sass, app/client/stylesheets/components/pu-invite-suggestions.sass, app/client/stylesheets/components/pu-navigation.sass, app/client/stylesheets/components/pu-page.sass, app/i18n/z-feat-invite-filters.en.i18n.json, app/i18n/z-feat-invite-filters.nl.i18n.json, app/packages/partup-client-invite-to-activity/InviteToActivity.html, app/packages/partup-client-invite-to-network/InviteToNetwork.html, app/packages/partup-client-invite-to-network/InviteToNetwork.js, app/packages/partup-client-invite-to-partup/InviteToPartup.html, app/packages/partup-client-invite-to-partup/InviteToPartup.js, app/packages/partup-client-pages/modal/invite_to_activity/invite_to_activity.html, app/packages/partup-client-pages/modal/invite_to_activity/invite_to_activity.js, app/packages/partup-client-pages/modal/invite_to_partup/invite_to_partup.html, app/packages/partup-client-pages/modal/invite_to_partup/invite_to_partup.js, app/packages/partup-client-pages/modal/network/network-invite.html, app/packages/partup-client-pages/modal/network/network-invite.js, app/packages/partup-client-upper-tile/InviteTile.html, app/packages/partup-client-upper-tile/InviteTile.js, app/packages/partup-server/methods/activities/activities_methods.js, app/packages/partup-server/methods/chatmessages/chatmessages_methods.js, app/packages/partup-server/methods/networks/networks_methods.js, app/packages/partup-server/methods/partups/partups_methods.js, app/packages/partup-server/services/matching_service.js
Implement new invite modal style and features
=> Feat invite filters

app/i18n/z-personalized-emails.en.i18n.json, app/i18n/z-personalized-emails.nl.i18n.json, app/packages/partup-server/event_handlers/invites/activities_invites_handler.js, app/packages/partup-server/event_handlers/invites/networks_invites_handler.js, app/packages/partup-server/event_handlers/partups/partups_invited_handler.js
=> Ft personalized emails

app/packages/partup-server/private/emails/base.html, app/packages/partup-server/private/emails/dailydigest.en.html, app/packages/partup-server/private/emails/dailydigest.nl.html, app/packages/partup-server/private/emails/partup_created_in_network.en.html, app/packages/partup-server/private/emails/partup_created_in_network.nl.html, app/packages/partup-server/private/emails/partups_networks_accepted.en.html, app/packages/partup-server/private/emails/partups_networks_accepted.nl.html, app/packages/partup-server/private/emails/partups_networks_new_pending_upper.en.html, app/packages/partup-server/private/emails/partups_networks_new_pending_upper.nl.html, app/packages/partup-server/private/emails/partups_networks_new_upper.en.html, app/packages/partup-server/private/emails/partups_networks_new_upper.nl.html, app/packages/partup-server/private/emails/partups_networks_upper_left.en.html, app/packages/partup-server/private/emails/partups_networks_upper_left.nl.html, app/packages/partup-server/private/emails/partups_new_comment_in_involved_conversation.en.html, app/packages/partup-server/private/emails/partups_new_comment_in_involved_conversation.nl.html, app/packages/partup-server/private/emails/partups_partner_request.en.html, app/packages/partup-server/private/emails/partups_partner_request.nl.html, app/packages/partup-server/private/emails/reset_password.en.html, app/packages/partup-server/private/emails/reset_password.nl.html, app/packages/partup-server/private/emails/upper_mentioned_in_network_chat.en.html, app/packages/partup-server/private/emails/upper_mentioned_in_network_chat.nl.html, app/packages/partup-server/private/emails/upper_mentioned_in_partup.en.html, app/packages/partup-server/private/emails/upper_mentioned_in_partup.nl.html, app/packages/partup-server/private/emails/verify_account.en.html, app/packages/partup-server/private/emails/verify_account.nl.html
Small copy changes to all email templates
=> fix(emails-copy): set Team Part-up as sender and small copy updates

app/i18n/phraseapp.en.i18n.json, app/i18n/phraseapp.nl.i18n.json
Exported the most recent locale files from PhraseApp
=> Updated translations from PhraseApp

app/i18n/phraseapp.en.i18n.json, app/i18n/phraseapp.nl.i18n.json, app/packages/partup-client-partupsettings/Partupsettings.html, app/packages/partup-client-partupsettings/Partupsettings.js
The keys are ready, translation for nl is pending
=> style(tooltip): Add ? explainer tooltip in create part-up form activity view 

app/packages/partup-client-dropdowns/chats/chat-notifications.html, app/packages/partup-client-dropdowns/chats/chat-notifications.js
The notification bulb on in the menu now properly closes when clicked.
=> Fix notification bulb

app/packages/partup-lib/services/validators.js
Tested with this perfect tool : https://regex101.com/r/pWd0Mp/3
[staging](https://fix-apostrophe.staging.part-up.com/)
=> fix(apostrophe): Apostrophe now working in tags

app/packages/partup-client-pages/app/home/blocks/Home_Header.js
When refreshing or returning to the home page while the scroll position is beyond the header it was impossible to scroll.
Closes #924
=> fix(scroll): allow scroll beyond header

CONTRIBUTING.md, README.md, RELEASING.MD
- describe branch usage now that develop has been decommissioned and master changed to only accept peer reviewed merge requests
- fix links that pointed to files on develop branch
- some boy scouting on 120 char line length
Interested by the way in how the "reviewers" requesting works. Should be able to be merged after 1 review, so hope it will not wait for @ralphboeije , @wouterd AND @jplattel :)
=> docs(master-branch): describe branch usage & fix links

CHANGELOG.md, package.json
@Krijger This is a bit annoying, can't release off master now. :)
=> chore(release): bump package version and update changelog

app/client/stylesheets/components/pu-coverheader.sass, app/packages/partup-client-pages/app/network/network.html, app/packages/partup-client-pages/app/network/network.js
Tribe sub-header is now clickable instead of just the 'start-button'.
Closes #919
=> Feat clickable tribeheader

app/packages/partup-client-base/client/uploader.js, app/packages/partup-client-media-uploader-button/MediaUploaderButton.html, app/packages/partup-client-media-uploader-button/MediaUploaderButton.js, app/packages/partup-client-pages/app/partup/document-renderer/document-renderer.html, app/packages/partup-client-pages/app/partup/document-renderer/document-renderer.js, app/packages/partup-client-pages/app/partup/updates/newmessage/newmessage.html, app/packages/partup-client-pages/app/partup/updates/newmessage/newmessage.js, app/packages/partup-lib/collections/files.js, app/packages/partup-lib/helpers/fileUploader.js, app/packages/partup-lib/helpers/url.js, app/packages/partup-lib/package.js, app/packages/partup-lib/schemas/update.js, app/packages/partup-lib/transformers/update.js, app/packages/partup-server/methods/updates/updates_messages_methods.js, app/packages/partup-server/package.js, app/packages/partup-server/publications/files.js, app/packages/partup-server/publications/updates.js, app/packages/partup-server/routes/files/files_routes.js, app/packages/partup-server/services/files_service.js
This PR allows all file types to be uploaded with the MediaUploadButton
=> Feat document upload

app/packages/partup-client-boardview/BoardView.js, app/packages/partup-client-boardview/package.js
=> fix(board): import sortable to boardview.js

app/client/stylesheets/components/layouts/_pu-layout--network.scss, app/packages/partup-client-pages/app/network/network.html
=> fix(tribe-navigation): Change spacing navigation dropdown

app/packages/partup-server/cron/update_sitemap.js
=> fix(sitemap): removed filtering of partup/network privacy types #1041

app/packages/partup-server/routes/hooks.js, app/packages/partup-server/routes/sitemap/sitemap_routes.js
Should fix #1051 (can't test from here)
=> feat(sitemap): added baseurl to separate sitemap file

app/packages/partup-client-dropdowns/tribes/tribes.js
- Tribes are now sorted alphabetically;
- The new update count is now visible again;
Closes: #1061 #1062
=> fix(mytribes-menu): Add tribe sort and restore updates visible

app/package.json, app/packages/partup-client-base/client/strings.js, app/packages/partup-client-pages/app/partup/activities/activity/view/view.html, app/packages/partup-client-pages/app/partup/activities/activity/view/view.js
The activity description is now shortened to 55 characters.
Closing #1068 
**Time**: About 3 hours (including research)
**Complexity**: 13
=> Shorten activity description on boardview cards

app/packages/partup-client-pages/app/partup/activities/activity/view/view.html, app/packages/partup-client-pages/app/partup/activities/activity/view/view.js
The activity dropdown on the boardview now allows for (un)archiving an activity.
Closes #1022
=> Feat activity dropdown archive

app/packages/partup-client-admin/Admin.html
Stats are now available in the dashboard
Closes: #1067
=> feat(admin-panel): Remove stats from admin overview

app/client/stylesheets/components/_pu-activity.scss, app/packages/partup-client-pages/app/partup/activities/activity/view/view.html, app/packages/partup-client-pages/app/partup/activities/activity/view/view.js
- Hover state 'edit' is now correctly positioned
- Hover state shows invite buttons on activity detail
- Markdown is now rendered on the activity
- Archived title color adjusted on hover
- Change spacing and positioning of invite buttons
Fixes: #1073
=> feat(activity): Improve activity design

app/.meteor/versions, app/client/stylesheets/components/_pu-list.scss, app/client/stylesheets/components/compositions/_pu-composition-partupdetailupdates.scss, app/packages/partup-client-1on1-chat/OneOnOneChat.js, app/packages/partup-client-1on1-chat/OneOnOneChatSidebar.js, app/packages/partup-client-pages/app/partup/activities/activities.html, app/packages/partup-client-pages/app/partup/activities/activities.js, app/packages/partup-client-pages/app/partup/partup-sidebar.js, app/packages/partup-client-pages/modal/invite_to_activity/invite_to_activity.js, app/packages/partup-client-pages/modal/invite_to_partup/invite_to_partup.js, app/packages/partup-lib/collections/updates.js, app/packages/partup-server/event_handlers/partups/partups_handler.js, app/packages/partup-server/methods/swarms/swarms_methods.js
=> Ft bugfixes

app/i18n/phraseapp.en.i18n.json, app/i18n/phraseapp.nl.i18n.json, app/packages/partup-client-dropdowns/notifications/notification/types/partup/archived.html, app/packages/partup-client-dropdowns/notifications/notification/types/partup/unarchived.html, app/packages/partup-client-resetpassword/Resetpassword.js
This solves #1088 @noelheesen or @ralphboeije would like your help with creating a phrase-app key :)
=> feat(reset-password): Phraseapp key for invalid password reset token

app/packages/partup-client-base/client/forms-mentionsInput.js, app/packages/partup-server/fixtures/users.js
It's now possible to mention people that have 3 words (or 2 spaces) in their names. The search will also start with 2 characters instead of 3.
There's one side note, example:
@Noel Heesen is mentioned
@Noel Heesen 'this' will still trigger a search because it's the 3rd word in a mention. if there are people with the same first two names this can result in conflict when entering the 3rd.
=> Fix mention suggestions

app/packages/partup-client-dropdowns/chats/chat-notifications.js
=> fix(chats): fixed loader

app/packages/partup-server/routes/csv/csv_routes.js
Improved the CSV upload to check for ; instead of a , . Also created a check if a row is not equal
to the length of 2.
This closes #959
=> fix(browser): CSV upload Checks for ; instead of , now

app/client/stylesheets/components/_pu-dropdownitem.scss, app/packages/partup-client-dropdowns/tribes/menustatemanager.js, app/packages/partup-client-dropdowns/tribes/requests.js, app/packages/partup-client-dropdowns/tribes/tribes.html, app/packages/partup-client-dropdowns/tribes/tribes.js, app/packages/partup-lib/collections/networks.js, app/packages/partup-lib/collections/partups.js, app/packages/partup-server/publications/users.js
@noelheesen can you see if you can fix the frontend? the backend now returns the upperdata again, just for the user that requested the overview.
=> Reinstate update counters in tribe menu

app/client/stylesheets/components/boardview/_boardview-card.scss, app/client/stylesheets/components/boardview/_boardview-lane.scss, app/packages/partup-client-boardview/BoardView.js, app/packages/partup-client-boardview/Sortable.js, app/packages/partup-client-boardview/package.js, app/packages/partup-client-pages/app/partup/activities/activity/activity.js
With this MR the cards can be dragged on all devices.
I'm a bit unsure about the offset we should use. This is the distance between the edge when the event should be triggered.
=> Make board cards draggable on all devices

app/client/stylesheets/components/_pu-dropdown.scss, app/packages/partup-client-dropdowns/tribes/menustatemanager.js, app/packages/partup-client-dropdowns/tribes/requests.js, app/packages/partup-client-dropdowns/tribes/tribes.html, app/packages/partup-client-dropdowns/tribes/tribes.js
Also changed the state manager update function to prevent a race condition which caused the network the user is a supporter off to be removed from the list.
Closes: #1149 #1167
=> fix(mytribes): Change menu to mobile version on all touch devices

app/client/stylesheets/components/_pu-page.scss, app/packages/partup-client-base/client/isMobile.js, app/packages/partup-client-dropdowns/chats/notification/chat-1-on-1-notification.js
- Users will still get redirected to the app on mobile devices;
Closes: #856
=> feat(chats): Enable chats on tablets

app/client/stylesheets/components/_pu-partuppagelayout.scss, app/packages/partup-client-pages/app/partup/partup-navigation.html, app/packages/partup-client-pages/app/partup/partup.js
- Title expands menu in collapsed state
- Increase clickable area around title
=> fix(sidebar): Title is now menu expander

app/packages/partup-client-pages/app/partup/partup-sidebar.js
This PR fixes a template exception #1111
=> fix(partup): fixed exception about privacy labels

app/packages/partup-lib/collections/users.js
This PR fixes the missing emails in the CSV export #1106
=> fix(csv): fixed missing email adresses in csv export

app/packages/partup-server/private/emails/partups_new_comment_in_involved_conversation.en.html, app/packages/partup-server/private/emails/partups_new_comment_in_involved_conversation.nl.html, app/packages/partup-server/private/emails/upper_mentioned_in_network_chat.en.html, app/packages/partup-server/private/emails/upper_mentioned_in_network_chat.nl.html, app/packages/partup-server/private/emails/upper_mentioned_in_partup.en.html, app/packages/partup-server/private/emails/upper_mentioned_in_partup.nl.html
This PR adds the noreply text to 3 relevant emails.
=> fix(email): add noreply to email copy

app/packages/partup-client-pages/app/profile/profile.js, app/packages/partup-lib/collections/users.js, app/packages/partup-server/seo/routes.js
This PR fixes deactivated users in issue #1180
=> Ft hide deactivated users

app/packages/partup-client-base/client/language.js, app/packages/partup-lib/schemas/register.js, app/packages/partup-lib/services/validators.js
Fixes an XSS attack posibility.
=> fix(profile): Disable XSS posibility on name field

app/client/stylesheets/components/_pu-profile.scss, app/packages/partup-client-pages/app/profile/profile.js
This PR fixes the expandable profile description #814
=> fix(profile): fixed profile description expand button

app/packages/partup-client-network-settings/NetworkSettings.html, app/packages/partup-lib/schemas/network.js
This PR eliminates the template error message in tribe-admin #1162
=> fix(network): fixed template exception for network tags

app/client/head.html, app/client/stylesheets/components/_pu-dropdown-add-media.scss, app/client/stylesheets/components/_pu-imagepreview.scss, app/client/stylesheets/main.scss, app/client/stylesheets/mixins/_user-select.scss, app/packages/partup-client-base/uploader/Pluploader.js, app/packages/partup-client-forminputs/fileinput.js, app/packages/partup-client-media-uploader-button/MediaUploaderButton.html, app/packages/partup-client-pages/app/partup/updates/newmessage/newmessage.html, app/packages/partup-client-partupsettings/Partupsettings.html, app/packages/partup-client-partupsettings/Partupsettings.js
When changing the browse_button it broke other places. It now defaults to the old button if it can find it.
Also changed the allowed extensions on partup-settings.
On iOS, Chrome there's a default touch-delay of 300ms, this will be fixed in a future release.
=> Fix browse button fallback

app/packages/partup-client-pages/app/partup/partup-navigation.html, app/packages/partup-client-pages/app/partup/partup.html, app/packages/partup-client-pages/app/partup/partup.js
=> fix(partup-sidebar): Set state before render

app/i18n/phraseapp.en.i18n.json, app/i18n/phraseapp.nl.i18n.json, app/packages/partup-client-pages/app/partup/updates/updates.html, app/packages/partup-client-pages/app/partup/updates/updates.js
=> feat(partup-docs): Add upload via new message to documents & links tab

app/i18n/phraseapp.en.i18n.json, app/i18n/phraseapp.nl.i18n.json, app/packages/partup-server/event_handlers/invites/networks_invites_handler.js
Added via Part-up to sentfrom address
=> Fix email sentfrom

app/packages/partup-lib/schemas/networkAccess.js
*note: not tested yet*
Closes: #914
=> feat($client): Increase character limit for tribe access levels

CONTRIBUTING.md, README.md
The docs needed an update to reflect recent changes for the installation and testing. Also updated the contribution guidelines!
=> Update docs for contributing

app/packages/partup-client-pages/modal/register/signup/signup.js
This PR fixes the saved user locale on sign-up 
Closes #1261
=> fix(locale): use correct locale helper to set locale on signup

app/packages/partup-client-pages/app/discover/partials/tribe-tile/tribe-tile.js, app/packages/partup-client-pages/app/network/start/Start_Chat.js
This PR fixes the partup stat on the discover page, the wrong one was being used. #1256
=> fix(discover): use correct partup count stat

app/client/stylesheets/components/_pu-avatar.scss
This PR fixes the missing remaining uppers from issue 
closes #828
=> fix(partup-tile): fixed missing remaining-uppers on partup tile

app/packages/partup-client-pages/modal/invite_to_activity/invite_to_activity.html, app/packages/partup-client-pages/modal/network/network-invite.html, app/packages/partup-client-upper-tile/InviteTile.html
This PR fixes issue
closes #1205
=> fix(translations): added translation keys as requested in #1205

app/packages/partup-server/event_handlers/chats/chatmessages_handler.js
This PR disabled the chat message scraper 
closes #885
=> fix(scraper): disabled chat message scraper #885

app/packages/partup-client-pages/app/partup/partup-navigation.html, app/packages/partup-client-pages/app/partup/partup-navigation.js, app/packages/partup-client-pages/modal/partup_settings/partup_settings.js, app/packages/partup-lib/collections/partups.js, app/packages/partup-server/methods/partups/partups_methods.js
Tribe admins do now have access to all part-up settings within that tribe. Also fixed the stop being a partner to show only when the user is a supporter of that part-up.
Closes: #1176 #1135
=> Tribe admins can now edit part-up settings

app/packages/partup-server/cron/send_daily_digest_users.js, app/packages/partup-server/event_handlers/chats/chatmessages_handler.js, app/packages/partup-server/event_handlers/invites/activities_invites_handler.js, app/packages/partup-server/event_handlers/invites/networks_invites_handler.js, app/packages/partup-server/event_handlers/networks/networks_handler.js, app/packages/partup-server/event_handlers/partups/partups_handler.js, app/packages/partup-server/event_handlers/partups/partups_invited_handler.js, app/packages/partup-server/event_handlers/partups/partups_uppers_handler.js, app/packages/partup-server/event_handlers/updates/updates_comments_handler.js, app/packages/partup-server/event_handlers/updates/updates_messages_handler.js, app/packages/partup-server/services/email_service.js, app/packages/partup-server/services/notifications_service.js
This PR will prevent any emails or notifications being sent to deactivated users 
closes #1252
=> Fix dont send email notifications deactivated users

app/client/stylesheets/components/compositions/_pu-composition-activity-invite.scss, app/client/stylesheets/components/compositions/_pu-composition-network-invite.scss
This PR fixes the scrolling bug on invite buttons closes #1199
=> Fix invite button

app/packages/partup-client-network-settings-partups/NetworkSettingsPartups.js
=> Fix tribesettings partupaccess

app/packages/partup-client-pages/app/partup/partup.js
On tablets the sidebar will now automatically show or hide based upon orientation.
Landscape === show;
Portrait === hide;
Closes: #1280
=> Feat auto sidebar mobile

app/packages/partup-lib/helpers/files/files.js
=> refactor(client): Changed max upload size to 20mb

app/packages/partup-client-base/client/forms-mentionsInput.js, app/packages/partup-client-pages/app/partup/partup-navigation.js, app/packages/partup-client-pages/app/partup/partup-sidebar.html
When mentioning someone with content after the mention, a space was sometimes not inserted, but the cursor was moved, thus connecting the mention and content. This change fixes this and checks it a space is present in the content. If no space is present, it is precatenated @noelheesen :P
=> Fix mention spacing

app/packages/partup-client-pages/app/partup/partup-navigation.js, app/packages/partup-client-pages/app/partup/partup-sidebar.html
Unpartner method should be called with a partupId, not a partup document. This closes #1287.
=> Fix unpartner button partup

app/packages/partup-client-pages/app/partup/activities/activity/form/form.html, app/packages/partup-client-pages/app/partup/activities/newactivity-restricted/newactivity-restricted.html
Consists of a minor change to set autofocus on activity modal input form.
=> Autofocus to activity modal input form

app/packages/partup-server/event_handlers/invites/activities_invites_handler.js, app/packages/partup-server/event_handlers/partups/partups_invited_handler.js
=> fix(email): Add via partup noreply to invite sender

app/client/stylesheets/components/boardview/_boardview.scss
In reference to issue [1352](https://github.com/part-up/part-up/issues/1352)
closes #1352
=> .pu-boardview-lane, added cursor: move; to line 15 of boardview.scss

app/packages/partup-client-boardview/Sortable.js
=> fix(client): Update SortableJS to 1.7.0

app/client/layout/main.html
I have updated the VWO script. The script is loaded after everything else, the link provided in #1395 states it should be included in the head tag. I don't know how I can test if including it at the bottom works so this might need change.
Closes #1395
=> feat(client): Update VWO script

app/packages/partup-client-dropdowns/dropdowns.js, app/packages/partup-client-dropdowns/notifications/notifications.js
=> fix(background): fixed dropdown toggle for a notification

app/packages/partup-client-pages/app/profile/profile.js
=> fix(avatar): fixed avatar error on click

app/packages/partup-client-network-settings-uppers/NetworkSettingsUppers.js
=> Fix network uppers infinitescroll

app/client/stylesheets/components/_pu-new-message.scss, app/client/stylesheets/components/_pu-popup.scss, app/packages/partup-client-boardview/BoardView.html, app/packages/partup-client-boardview/BoardView.js, app/packages/partup-client-comments/Comments.html, app/packages/partup-client-files/file-controller.js, app/packages/partup-client-files/pickers/device-picker/device-picker.js, app/packages/partup-client-files/renderers/document-renderer/document-renderer.js, app/packages/partup-client-pages/app/partup/activities/activities.js, app/packages/partup-client-pages/app/partup/activities/activity/form/activity.js, app/packages/partup-client-pages/app/partup/activities/activity/view/view.html, app/packages/partup-client-pages/app/partup/activities/activity/view/view.js, app/packages/partup-client-pages/app/partup/gallery/gallery.js, app/packages/partup-client-pages/app/partup/partup.js, app/packages/partup-client-pages/app/partup/updates/message-form/message-form.html, app/packages/partup-client-pages/app/partup/updates/message-form/message-form.js, app/packages/partup-client-pages/app/partup/updates/updates.html, app/packages/partup-client-pages/app/partup/updates/updates.js, app/packages/partup-client-spinner/Spinner.js, app/packages/partup-client-update/Update.js, app/packages/partup-lib/collections/files.js, app/packages/partup-lib/collections/images.js, app/packages/partup-lib/collections/users.js, app/packages/partup-server/methods/files/files_methods.js, app/packages/partup-server/methods/images/images_methods.js, app/packages/partup-server/publications/activities.js, app/packages/partup-server/publications/updates.js
- Three main subscriptions in partup.js
- Moved file subsriptions to the three main subs
- Replaced the rest of file subs with Meteor.calls
=> fix(subscriptions): (Re)move and replace subscriptions

.vscode/settings.json, app/packages/partup-client-pages/app/partup/partup-sidebar.html
=> Fix takepart partup

.vscode/settings.json, app/client/stylesheets/components/_pu-dropdown.scss, app/i18n/phraseapp.en.i18n.json, app/i18n/phraseapp.nl.i18n.json, app/packages/partup-client-dropdowns/menu/menu.html, app/packages/partup-client-dropdowns/profile/profile.html, app/packages/partup-client-pages/app/home/blocks/Home_Footer.html
=> Feat menu organisations

app/packages/partup-client-files/pickers/drive-picker/drive-picker.js
Includes the new scope for uploading files. The other scope for translation is still in progress.
=> Feat update googledrive scope

app/packages/partup-client-update/Update.js, app/packages/partup-client-update/types/message-added.html, app/packages/partup-client-update/types/message-added.js
The update id is now properly passed to the popup again
closes: #1472
=> Fix editmessage

app/package.json, app/packages/partup-lib/transformers/update.js, app/packages/partup-server/event_handlers/activities/activities_handler.js, app/packages/partup-server/event_handlers/updates/updates_comments_handler.js
The following will be included in the documents and links tab:
* Activities with files;
* Activities with a link in description;
* Comments with a link;
=> Feat document tab

app/packages/partup-client-files/pickers/drive-picker/drive-picker.js
The new scope does not include access for setting permissions, see https://github.com/part-up/part-up/commit/1be159d8c21d0a7a988e0263f1d641d3e790f748
=> fix(client): No longer set permissions for drive files

app/client/stylesheets/components/_pu-activity.scss, app/packages/partup-client-comments/Comments.html, app/packages/partup-client-comments/Comments.js, app/packages/partup-client-pages/app/partup/activities/activity/view/view.html, app/packages/partup-client-pages/app/partup/activities/activity/view/view.js, app/packages/partup-client-update/Update.html, app/packages/partup-client-update/Update.js
Tested on IE/Chrome/FF
Closes #1454
=> fix(client): X comments always directs to update detail

app/client/stylesheets/components/_pu-update.scss
Time spend: 5min
Tested on IE/Chrome/FF
Closes #1428
=> fix(client): Put timeline behind comment block

app/packages/partup-client-pages/app/partup/activities/activities.html, app/packages/partup-client-pages/app/partup/activities/activity/activity.html, app/packages/partup-client-pages/app/partup/activities/activity/view/view.js
Always hide the comments on activity listview.
Tested on IE/Chrome/FF
Closes #1430
=> feat(client): Hide comments on activity list view

app/package.json, app/packages/partup-client-base/client/browser.js, app/packages/partup-client-boardview/BoardView.js, app/packages/partup-client-boardview/Sortable.js, app/packages/partup-client-boardview/package.js
Chrome and Safari now use fallback DnD instead of the new HTML5 DnD which is buggy in those browsers.
Re-modified the new version of Sortablejs to add an offset for Android touch delay. I'm working on a permanent fix and have made a PR that will prevent the need for modification of the library everytime we need to update it and made a PR I hope will be accepted soon https://github.com/RubaXa/Sortable/pull/1266
This PR still needs testing on
* Mac
* iOS
Tested on:
* Win
* FF;
* Chrome
* IE11
* EDGE
* Linux
* FF;
* Chrome;
* Android
* Chrome
Closes: #1497 #1483
=> Fix board drag

app/client/stylesheets/components/_pu-activity.scss, app/client/stylesheets/components/_pu-contribution.scss, app/packages/partup-client-contribution/Contribution.html, app/packages/partup-client-pages/app/partup/activities/activity/view/view.html, app/packages/partup-client-pages/app/partup/activities/activity/view/view.js
=> feat(client): Add grayscale to icons belonging to unverified contributions

app/client/stylesheets/components/_pu-form-popup.scss, app/i18n/phraseapp.en.i18n.json, app/i18n/phraseapp.nl.i18n.json, app/packages/partup-client-pages/app/partup/activities/activity/form/activity.html, app/packages/partup-client-pages/app/partup/activities/activity/form/activity.js
Users are now able to self assign when creating an activity.
Closes #1461
=> feat(client): Add do this button to create activity form

app/client/stylesheets/defaults/_typography.scss
=> fix(style): Changed list-style of ol elements to decimal

app/client/head.html, app/packages/partup-client-files/pickers/onedrive-picker/OneDrive.js, app/packages/partup-client-files/pickers/onedrive-picker/onedrive-picker.js, app/public/onedrive/oauth_receiver.html
=> Fix onedrive picker

app/packages/partup-client-pages/app/partup/activities/activity/view/view.html, app/packages/partup-client-pages/app/partup/activities/activity/view/view.js
=> fix(client): Allow partners to edit activities

app/packages/partup-lib/features.js, app/packages/partup-lib/package.js, app/packages/partup-lib/routes.js
This PR makes it easier to manage feature flags when/if we need them in the future.
Closes #1555
=>  feat(features): Always enable flags on development

app/packages/partup-client-dropdowns/notifications/notification/types/network/partup-created.html, app/packages/partup-server/event_handlers/partups/partups_handler.js
To test:
1. Login with default user;
1. Check newest notification.
Closes: #1581
=> fix(client): Change route to partup-home for partup_created notificaion

app/packages/partup-client-pages/app/partup/activities/activity/form/activity.html, app/packages/partup-client-pages/app/partup/activities/activity/view/view.html
=> fix(client): Disable new activity-form actions in create partup flow

app/packages/partup-client-files/pickers/drive-picker/drive-picker.js
=> feat(client): Enable TeamDrives

app/packages/partup-server/publications/updates.js
The mobile app still relies on `updates.one` instead of the new `updates.single`.
=> fix(mobile): Add mobile subscription

app/packages/partup-client-pages/app/network/partials/joinbutton.html, app/packages/partup-client-pages/app/network/partials/joinbutton.js, app/packages/partup-client-pages/app/network/start/Start_Header.html, app/packages/partup-client-pages/app/network/start/Start_JoinButton.html, app/packages/partup-client-pages/app/network/start/Start_JoinButton.js, app/packages/partup-client-pages/app/network/start/Start_MostActive.html, app/packages/partup-client-pages/app/network/start/Start_Video.html, app/packages/partup-client-pages/app/network/start/Start_Video.js
When accepting an invite the go-to-tribe button should now render properly on the front-page. (instead of a request invite)
closes #1626
=> Fix go tribe button

app/.meteor/packages, app/.meteor/versions, app/packages/partup-client-base/bootstrap.js, app/packages/partup-server/methods/users/users_methods.js, config/development/env.dist
The following environment variable needs to be set in meteor settings.
```
"intercom": {
"secret": ...
}
```
@wouterd Can you add this variable as in the env.dist?
=> feat(intercom): Add identity verification

app/client/stylesheets/components/_pu-button.scss, app/client/stylesheets/components/compositions/_pu-composition-register.scss, app/packages/partup-client-pages/modal/register/signup/signup.html, app/packages/partup-client-pages/modal/register/signup/signup.js, app/packages/partup-lib/collections/users.js, app/packages/partup-server/accounts.js, app/packages/partup-server/services/email_service.js
This PR will always send a verification email regardless of the signup method (facebook, linked-in).
When a user has an email address that isn't verified a new verification mail will be send instead of the notification.
Closes: #1640
=> feat(signup): Double opt-in

app/.meteor/packages, app/.meteor/versions, app/packages/partup-client-popup/Popup.js, app/packages/partup-lib/collections/users.js, app/packages/partup-server/services/notifications_service.js
=> fix(import): Fix notification model import statement

app/packages/partup-lib/routes.js, app/packages/partup-server/services/email_service.js
This PR let's user's visit a partup by token in order to request access.
Closes: #1671 
Note: an invited user still doesn't show in the invited tab.
=> Fix invite by email flow

app/i18n/phraseapp.en.i18n.json, app/i18n/phraseapp.nl.i18n.json, app/packages/partup-client-pages/app/404/partup/closed.html, app/packages/partup-client-pages/app/404/partup/closed.js, app/packages/partup-client-pages/package.js
=> Add signup/login to part-up closed page

app/packages/partup-client-profilesettings/Profilesettings.html
=> fix(profile-settings): Removed phone & skype input from profile settings

app/packages/partup-server/services/participation_calculator_service.js
The new formula better reflects user activity since contribution's can no longer be rated.
Closes: #1644
=> Adjust user participation score calculations

app/i18n/phraseapp.en.i18n.json, app/i18n/phraseapp.nl.i18n.json, app/packages/partup-client-base/client/language.js, app/packages/partup-client-login/Login.js
And display which actions to take to reactivate the account.
fix #1646
=> feat(user): When a deactivated user tries to login, show a warning to the user

app/client/stylesheets/components/_pu-activity.scss, app/client/stylesheets/reset.css
All links are now orange by default.
=> style(link): Make links orange by default

app/package-lock.json
Adds trumbowyg to package lock.
=> chore(packages): Update package-lock.json

app/packages/partup-lib/collections/users.js, app/packages/partup-server/private/emails/verify_account.en.html, app/packages/partup-server/private/emails/verify_account.nl.html, app/packages/partup-server/services/email_service.js, app/packages/partup-server/services/notifications_service.js
Tested locally, to be fully tested on beta.
=> feat(opt-in): Only send verification mails once a week on update

app/client/stylesheets/components/_pu-block.scss, app/packages/partup-client-base/client/html/html.js
=> fix(wysiwyg): No longer remove some html tags when processing html

app/client/stylesheets/components/_pu-header.scss
=> fix(modal): Darken color of modal close button on hover

app/packages/partup-client-pages/app/profile/tabs/about.js
=> fix(profile): Refresh profile template on tiles change

app/client/stylesheets/components/_pu-activity.scss, app/client/stylesheets/components/myactivities/_my-activities.scss, app/client/stylesheets/main.scss, app/i18n/phraseapp.en.i18n.json, app/i18n/phraseapp.nl.i18n.json, app/package-lock.json, app/package.json, app/packages/partup-client-base/bootstrap.js, app/packages/partup-client-dropdown/dropdown.js, app/packages/partup-client-dropdowns/profile/profile.html, app/packages/partup-client-login/Login.js, app/packages/partup-client-pages/app/my_activities/my-activities.html, app/packages/partup-client-pages/app/my_activities/my-activities.js, app/packages/partup-client-pages/app/partup/activities/activity/activity.html, app/packages/partup-client-pages/app/partup/activities/activity/form/activity.js, app/packages/partup-client-pages/app/partup/activities/activity/view/view.html, app/packages/partup-client-pages/app/partup/activities/activity/view/view.js, app/packages/partup-client-pages/package.js, app/packages/partup-lib/collections/invites.js, app/packages/partup-lib/routes.js, app/packages/partup-lib/schemas/activity_invite.js, app/packages/partup-server/methods/activities/activities_methods.js, app/packages/partup-server/methods/contributions/contributions_methods.js, app/packages/partup-server/publications/activities.js, app/packages/partup-server/publications/invites.js
Translation files are updated, merge into PhraseApp after closing this PR.
Closes: #1744
=> feat(activities): Add my activities overview

app/packages/partup-lib/collections/users.js, app/packages/partup-server/services/matching_service.js
This reverts commit 0a983b10a605229a602a8e8d8ca14dd93f82e249.
=> Revert "style(test): Log invite query for testing"

app/packages/partup-server/services/matching_service.js
=> fix(invite): Don't exclude uppers on activity invite

app/packages/partup-client-pages/app/partup/activities/activity/form/activity.html
=> fix(form): Set button types for submit

app/packages/partup-client-forminputs/datepicker.js, app/packages/partup-server/methods/activities/activities_methods.js
=> fix(activity): Unset end_date when not present on update

app/packages/partup-lib/transformers/activity.js, app/packages/partup-server/methods/activities/activities_methods.js
Closes: #1785 
The bug for removing description existed since https://github.com/part-up/part-up/commit/b521b82b7582d509dbe4b0096227be78f86daa72 which was 13 months ago :|
=> fix(activity): You can now remove an activity description

app/packages/partup-client-base/client/notify.js, app/packages/partup-client-login/Login.js, app/packages/partup-client-pages/modal/register/signup/signup.js
=> fix(toastr): add options to toastr for increased timeout duration

app/packages/partup-lib/collections/users.js
This might fix the mongo error about query 1000+ no index
=> fix: ensure index for profileVisibility
