part-up/part-up

- app/packages/partup:client-hover-container/HoverContainer.js
Fix the bug where the hover-container (shown when hovering over a user-avatar) never disappears until route change.
> Fix: hovercontainer doesn't disappear

- app/packages/partup:server/fixtures/images.js
- docker-compose.yml
Images are now pulled from our own s3 bucket. Starting with a fresh mongo db on dev made meteor crash due to a domain no longer existing.
> fix(bootstrap): all images are available again.

- app/packages/partup:server/routes/composite.js
Allow CORS from all origins in HTTP calls on behalf of the [Part-up app](https://github.com/part-up/app) (subscriptions and methods already do that).
> Allow CORS in HTTP calls

- app/packages/partup:lib/collections/images.js
I made a list of all images that every notification template try to render and came to the conclusion that not all those images are also published. They may still work when the page does a coincidental publication of that image, but I fixed the publication to ensure all images are correctly being published with the notifications.
Relative to the Part-up website, even more notification images are broken in the Part-up app since there is no other subscription that possibly could publish the images coincidentally.
> Notifications images publication

- app/packages/partup:lib/collections/images.js
- app/packages/partup:server/publications/updates.js
Avatars of authors of comments on updates from Part-ups do actually work, due to the Supporters and Partners subscription in the Part-up sidebar. But in the app there is no such subscription. The images should be shipped with the publication for Part-up updates. For the website, this won't matter in download size or speed of any kind. It's just an insurance for the comment author avatars to appear.
It's just another publication fix like PR #396.
> Partup updates comments author avatar images publication

- app/packages/partup:server/event_handlers/contributions/contributions_handler.js
- app/packages/partup:server/event_handlers/ratings/ratings_handler.js
Generally spoken, the conversation linked to a notification are the comments on the update from `notification.type_data.update._id`. Though, for the following notification types this is not the case.
partups_contributions_proposed
partups_contributions_inserted
contributions_ratings_inserted
This fix puts these notifications back into consistency and fixes the link behind these notifications in the dropdown menu. This PR will also fix the notification-related conversation in the app for these notification types.
> Fix notifications typedata

- Dockerfile
This will speed up image uploads. The graphicsmagick node package uses /tmp to store uploaded images for processing.
> Added volumes for /tmp and /var/tmp

- app/packages/partup:lib/collections/networks.js
- app/packages/partup:server/publications/users.js
Some intended paginations couldn't have worked. These routes need to correctly support pagination to realise infinite scroll in the part-up app (and in web, too).
> Fix paginations

- app/.meteor/packages
- app/scss.json
A while ago we removed the standard-minifiers-css package by replacing standard-minifiers by standard-minifiers-js. (standard-minifiers contains both standard-minifiers-css and standard-minifiers-js). We did that because we thought it didn't split the resulting CSS file correctly for IE9 (due to max 4095 selectors limit). But it actually does, but only in production mode.
So this pull request re-enables CSS auto-vendor-prefixing and CSS minification to improve speed and compatibility. It fully works on IE with a non-development build.
> Re-enable css processing (minification and autoprefixer)

- app/packages/partup-server/bootstrap.js
Sets two extra HTTP headers so that meteor can live without an nginx in front.
> feat(security): Added HSTS and XSS Protection headers

- app/packages/partup-server/cron/update_shared_count.js
- app/packages/partup-server/cron/update_swarm_shared_count.js
- app/packages/partup-server/services/shared_count_service.js
Twitter discontinued the API we used. The Search API only returns the last 7 days, so that's also not going to work.
If we want to keep this count we need to implement a Twitter Streaming API client and process the counts ourselves.
See: https://dev.twitter.com/streaming/reference/post/statuses/filter
> Removed Twitter share counts because api is no longer available

- app/packages/partup-client-dropbox-chooser/DropboxChooser.ctrl.js
According to the [api documentation](https://www.dropbox.com/developers/documentation/http/documentation#sharing-create_shared_link_with_settings) Dropbox only allows paying accounts to set an expiring date. This changes commit 69d56db
Fixes #964
> fix(dropbox-chooser): Remove link expiration

- app/packages/partup-client-dropbox-chooser/DropboxChooser.ctrl.js
Dropbox direct links expire after four hours, switched to preview links.
> fix(dropbox-chooser): Set linkType to preview

- app/.meteor/versions
- app/packages/partup-server/package.js
- app/packages/partup-server/publications/networks.js
- app/packages/partup-server/routes/middleware.js
Probably fixed #1018 .
Added two middlewares that expose the userID from the sent bearer token.
simple:rest then makes sure the publishComposite and publish functions also get their this.userId set.
This change probably means that the middleware written that exposes the user on the request can now be safely deleted and rest endpoints accepting user ids can now be rewritten too.
> fix(rest): rest routes now have userId exposed to publications

- app/packages/partup-client-pages/modal/invite_to_activity/invite_to_activity.js
Email invites now won't show up as user tile in the pending tab
Fixes: #1038
> fix(invite-activity): Filter email invites

- app/packages/partup-client-base/marketo.js
- If the user accepted after the window was loaded the window.onload event already fired and thus never triggering the marketto script;
Fixes: #1038
> fix(marketo): Change handle accept event

- app/packages/partup-client-dropdowns/tribes/tribes.html
- app/packages/partup-client-dropdowns/tribes/tribes.js
- app/packages/partup-lib/collections/users.js
The Networks the user was not a member of were not shown, even if the user was partner or supporter in one of it's partups. The My Tribes menu now loads all networks related to partups where the user is partner or supporter. 
**Testcase**:
1. Login as judy@ and click the My Tribes menu;
2. You should see 2 tribes, ING and Lifely;
3. Judy is not a member of ING, should go to the landing page on click;
4. Judy is a member of Lifely, should go to the partup overview page on click;
**_Not tested_**: The user is associated with many partups within a couple of networks and loading takes longer than 3 seconds. Since the technique to load the networks has changed a race condition may occur.
Closes: #1050
> Fix My Tribes menu

- app/packages/partup-client-dropdowns/tribes/tribes.js
Menu now only shows tribes that are not archived
Tested locally by archiving 1 tribe in the fixtures.
Closes #1060
> fix(mytribes-menu): Add archived_at filter to tribes

- app/client/stylesheets/components/compositions/_pu-composition-profilesettings-email.scss
- app/packages/partup-client-dropdowns/notifications/notifications.js
- app/packages/partup-client-pages/modal/profile_settings/notifications/notifications.html
Because the wrapper was a button the browser did not recognize clicks on elements inside the button but only to the wrapper button itself. Changed the wrapper button element to a div element.
Tested on: 
WIN10: Chrome, Edge (2 devices) and IE
Linux: Chrome, FF
**Complexity**: 13
**Time**: 15 minutes
Closes #838
> fix(toggle-notifications): Change wrapper from button to div

- app/client/stylesheets/components/_pu-page.scss
- app/packages/partup-client-pages/modal/invite_to_activity/invite_to_activity.html
- app/packages/partup-client-pages/modal/invite_to_partup/invite_to_partup.html
- app/packages/partup-client-pages/modal/network/network-invite.html
- Lower padding-top for page
- Only display description on desktop screens
As my screen shows the tiles by default I can not test if what I did helped, ***please check if the invite button is now visible on macbooks before accepting the request.***
#1055
> feat(invite-modal): Make invite button visible for first tiles

- app/client/stylesheets/reset.css
The bootstrap.scss file had an underline on :hover, :focus. This is now countered by specifying 'none' in the reset.scss file
Fixes: #1078
> fix(style): Remove underline from hyperlink hover

- app/i18n/phraseapp.en.i18n.json
- app/i18n/phraseapp.nl.i18n.json
- app/packages/partup-client-dropdowns/menu/menu.html
- app/packages/partup-client-pages/app/home/blocks/Home_Footer.html
This completes #1090, by adding the assigned links in the dropdown menu and footer.
> feat(menu): Added instruction videos link to menus

- app/packages/partup-server/methods/partups/partups_methods.js
If the user creates a partup in a public tribe where the user is not a member of, the user now
automatically becomes a member.
#1021
> fix(browser): A user joins a tribe when a partup is created by the user

- app/packages/partup-server/routes/csv/csv_routes.js
CSV bulk invite route now trims names and lowercases of emails
#959
> fix(browser): CSV bulk invite now trims names and lowercases emails

- app/packages/partup-client-dropdowns/tribes/tribes.js
The mytribes menu now sorts ignoring any upper or lower case characters
#1109
> fix(tribes-menu): Make sorting case-insensitive

- .babelrc
- app/.babelrc
Meteor 1.5.1 build changes how babel should be handled. Further investigation wanted, we still have import / dependencies around the old way of handling babel.
> fix(babel): Remove babelrc files because meteor upgrade to 1.5

- app/client/stylesheets/font-faces/_open-sans.scss
- app/client/stylesheets/font-faces/_picons.scss
- app/iconfont.json
- devops/provision/roles/loadbalancer/files/partup-maintenance/css/font-faces.css
After the migration from SASS to SCSS the italic font broke and part-up icons could not be loaded anymore.
> Fix: font loading error in IE11

- app/client/stylesheets/reset.css
Autoform tags uses bootstrap which gives conflicts with our styling. Each update caused bootstrap to
be included again so I've overwritten this in the reset.css
Closes: #1068
> fix(CSS): Overwrite conflicting styles in bootstrap

- app/.meteor/versions
- app/client/stylesheets/components/boardview/_boardview-card.scss
- app/client/stylesheets/components/boardview/_boardview-lane.scss
- app/packages/partup-client-boardview/BoardView.js
- app/packages/partup-client-boardview/Sortable.js
Lanes and cards now use the desired scrolling behavior and default touch actions are now prevented.
Closes: #1148
> fix(activity-board): Only set delay on iOS and add css for overlow

- app/packages/partup-client-dropdowns/chats/chat-notifications.js
- app/packages/partup-client-dropdowns/chats/notification/chat-group-notification.js
Just like the one-on-one chats.
The list container will scroll to top on switching chat-types.
Closes: #1193
> Allow tribe-chats on tablets

- app/client/stylesheets/components/_pu-partuppagelayout.scss
- app/packages/partup-client-dropdowns/partials/partup/navigation.js
- app/packages/partup-client-pages/app/partup/partup-navigation.html
- app/packages/partup-client-pages/app/partup/partup.js
- Sidebar width: 95%, max $sidebar-width
- Add filter to content when sidebar expanded
- Include settings cog in dropdown
If we wan't the filter to include the navigation-header then I have to adjust some css.
> fix(partup-layout): Improve element layout for mobile

- app/packages/partup-client-comments/Comments.js
This PR fixes the error message on the create_comment field #946
> fix(comments): fixed error handling of comment field limit

- app/packages/partup-lib/transformers/activity.js
- app/packages/partup-server/methods/activities/activities_methods.js
This PR fixes the unwanted removal of lane tags off activities on save #881
> fix(activity-update): don't remove lane_id on update

- app/client/stylesheets/defaults/_body.scss
Will now display the toastr above the intercom button, this is testable by adding an invalid file via a message. This can either be a file larger than 5mb or a file with an extension that is not allowed. The latter can be done by changing the file options to all files in the file browse dialog.
> feat(toastr): Change toastr position to above intercom button

- app/packages/partup-client-boardview/BoardView.js
- app/packages/partup-client-boardview/Sortable.js
This change affects every device.
- Touch delay is set to 400ms;
- Touch delay is only active on Tablet or Mobile devices;
- Touch delay now also works for lanes;
To test:
1. Scroll horizontally on the lane-header.
1. Scroll vertically inside a line when starting on a card.
In both cases you should be only able to move the item if you hold your finger still for the duration of the delay.
Time spent: 1h37m
Closes: #1201
> fix(client): Add touch delay on android for the boardview

- app/client/stylesheets/components/_pu-app.scss
- app/client/stylesheets/components/_pu-partuppagelayout.scss
- app/client/stylesheets/components/boardview/_boardview.scss
This PR fixes lanes collapsing on screens with little height. A minimum height of 375px is set to all lanes.
The main part-up header that is on all pages is now positioned fixed instead of relative. This fixed a bug that caused extra space below the boardview. This means that every page on the platform is touched by this PR. I haven't found any differences so far while testing on staging.
Closes: #1239
> Fix boardview scroll landscape

- app/packages/partup-client-base/helpers/screenSize.js
This is needed in order to update the ui when the orientation of a device has changed
*p.s. this is awesome and should be implemented to more functionalities*
Closes: #1278
> fix(client): Make `screenHelper` template helpers reactive

- app/packages/partup-client-pages/app/discover/partials/tile/active.html
This PR re-enabled the hovercards on discover page
> fix(discover): re-enabled upper hover cards on discover page

- app/packages/partup-client-base/helpers/autolink.js
After the update the Autolinkjs API changed, I've read this but did not include all necessary steps to accommodate this change.
> fix(client): Fix autolinker after update

- app/packages/partup-client-pages/app/partup/partup-sidebar.html
Instead of today's date, the sidebar now shows the correct date when a part-up was archived
This solves #1085.
> fix($partup): Sidebar now shows the right date when a partup was archived

- app/packages/partup-client-boardview/BoardView.js
When an activity was removed, it was shown striketrough on the activity view in board-mode. This
commit fixes this error and hides this activity: #1305
> fix(board): A removed activity now doesn't show up the lanes anymore

- app/.meteor/packages
- app/packages/partup-server/routes/files/files_routes.js
This fix removes the fast click library to fix the bugs with upload button on mobile devices. The package introduced an unnecessary delay which resulted in several bugs. 
Logging for uploaded files is also removed as @noelheesen  needed some data about the magic bytes.
> fix($meteor): Remove fastclick and file upload logging

- app/packages/partup-client-comments/Comments.html
- app/packages/partup-client-comments/Comments.js
- app/packages/partup-client-update/Update.js
The selector for selecting the right form was broken due to `_.uniqueId()` used as a prefix in the commentform ID. Changed the selector for focus to match only at the end of the string.
> fix($meteor): Comment button on updates now applies focus to the form field

- app/packages/partup-client-boardview/BoardView.js
When pressing enter when trying to add a new lane, Firefox on Mac does not blur and thus does not
trigger the adding of the lane, this fix forces a blur trough jQuery and triggers it anyway
closes #1312 and closes #1160
> fix($browser): This fixes the new lane input on firefox

- app/packages/partup-client-hover-container/HoverContainer.js
- app/packages/partup-client-pages/app/discover/partials/tile/active.html
The hover container expected an userId in data-hovercontainer-context, but used .attr to get the
attribute, but not the value, this commit fixes this by using .data() instead
This closes #1314 (and closes #1293 for me locally but validation would be nice)
> fix($meteor): Fixes the upper hover container for partup tiles

- app/packages/partup-client-base/client/logger/formats/no.js
- app/packages/partup-client-base/client/logger/formats/no.test.js
- app/packages/partup-client-base/client/logger/formats/tapi18n.js
- app/packages/partup-client-base/client/logger/formats/tapi18n.test.js
- app/packages/partup-client-base/client/logger/plogger.js
- app/packages/partup-client-base/client/logger/plogger.test.js
- app/packages/partup-client-base/client/logger/transports/console.js
- app/packages/partup-client-base/client/logger/transports/toastr.js
- app/packages/partup-client-base/package.js
I was having a look at [winston](https://github.com/winstonjs/winston) to see if it was possible to use it on the client as well. After playing around a bit I found that v3.0.0rc provides excellent flexibility to do so.
Why use winston on the client? When working on the uploader I found that I don't want error messages to be displayed in the toastr when working in development config and I had no means to do so, it was one or the other. Winston provides a great way to seperate formatting and transporting logs from the logging logic itself, enabling different formats and transports for each log level based on the environment it's running in.
**Testable by using the logger in the browser console**
// Current way to display a toastr:
`Partup.client.notify.error(TAPi18n.__(error.reason || …
> feat(client): Implement client side logger

- app/package.json
Added winston to the deps so it will always include even in prod. Can't test this locally, it works without this change even when I run `meteor run --production`.
> fix(meteor): Add winston to package.json

- app/packages/partup-lib/services/validators.js
Changing the regex for the LinkedInUrl validator to accept company urls. 
Side-effect: it's now possible to use company urls in your own profile as well.. If we don't want this we might want to implement 2 different validators, @ralphboeije?
This closes: #1378.
> fix($schema): LinkedInUrl validator now accepts company urls

- app/packages/partup-lib/helpers/files/_filemap.js
- app/packages/partup-lib/helpers/files/files.js
- app/packages/partup-lib/helpers/files/files.test.js
The info[0] object never returns false. I meant to check if info[0] was a FileInfo object itself. This happens when the lookup is done via mime `type` and multiple FileInfo objects found.
> fix(client): Properly extract file icon when multiple info objects found

- app/packages/partup-server/constants.js
- app/packages/partup-server/event_handlers/invites/activities_invites_handler.js
- app/packages/partup-server/event_handlers/invites/networks_invites_handler.js
- app/packages/partup-server/event_handlers/partups/partups_invited_handler.js
This pull requests fixes the fromAddress header for all invites send from Part-up. It also now includes the notification@part-up.com email and a new text for `(no reply)` because of RFC822!
> Fix Email Invite copy

- app/package.json
- package-lock.json
The update of sanitize-html comes with postcss for inline-style parsing. postcss includes ansi-style written in ES6. As packaegs won't get transpiled it gives an error in IE.
> fix(build): Sanitize-HTML version locked to not include 'postcss'

- app/client/stylesheets/components/_pu-partuppagelayout.scss
Hides the vertical and horizontal scrollbars that apply to the 'partuplayout' wrapped element in IE11
PS. all the indentation has changed so it detects a lot of changes.
> fix(client): Hide scrollbar mainlayout IE11

- README.md
- app/package-lock.json
- app/package.json
We already use ESLint for checking code. Prettier lives besides ESLint and will re-write the code in the format specified by ESLint and Prettier. In order for them to do this automatically a configuration file must be added for your IDE. I've updated the readme.md to include an example for vscode.
> Prettier automatically applies code conventions from ESLint

- app/packages/partup-client-pages/app/partup/activities/activity/view/view.html
- app/packages/partup-client-pages/app/partup/activities/activity/view/view.js
- app/packages/partup-client-update/types/message-added.html
- app/packages/partup-client-update/types/message-added.js
Show more menu when the user is able to see an entry instead of checking if the user is a supporter.
Time spend: 15mins
Closes: #1505
> fix(client): Make more menu available to update owner

- app/packages/partup-client-base/bootstrap.js
- app/packages/partup-client-base/client/language.js
- app/packages/partup-lib/collections/users.js
Disabled setting the locale when a user is in the middle of the logging in process. This caused the handler to be ran twice and trigger a race condition. The race condition was caused by always updating the user object in the database even when the user already had the locale that was being updated. That triggered the handler to be ran again and got in a loop until they were the same as the cached language.
Complexity: 25
Time spent: 7hrs~
Closes: #1502
> Fix language bug

- app/packages/partup-client-header/Header.html
Note: The login button disappears on screens with a width smaller than 485px (no more room).
Closes: #1583
> fix(client): Add language selector for logged out users

- app/packages/partup-client-login/Login.html
Instead of a scrollable footer, we can just use a label to align everything
fix #1623
> fix(login): Fixed the floating login button

- app/packages/partup-server/publications/chats.js
A subscription would be created when navigating to /chats, this fixes the backend match failed
> fix(chats): Fixed match error when no chatId is present

- app/package-lock.json
- app/packages/partup-client-update/Update.js
- app/packages/partup-server/methods/users/users_methods.js
The update detail no longer relies on existing subscriptions. In some cases the user that triggered the update is no longer an upper or supporter in the given part-up which caused this bug.
Closes #1627
> fix(update): Always get the user on update detail

- app/packages/partup-client-comments/Comments.js
The profile image id was stored with the comment instead of getting it from a user itself that is
referenced in the comment.
fix #1553
> fix(comments): A profile image was reference by the image id stored in the comment

- app/packages/partup-client-pages/modal/profile_settings/advanced/advanced.html
This corrects the phraseapp keys in code:
prefix: `modal-profilesettings-advanced-`
keys:
- `impersonation-title`;
- `impersonation-description`;
- `impersonation-label`;
> refactor(translation): Rename impersonation translation keys

- app/packages/partup-client-hover-container/templates/upper.html
- app/packages/partup-client-hover-container/templates/upper.js
- app/packages/partup-lib/collections/users.js
Uses findSinglePublicProfile to guard deactivated/deleted users;
Disables the endless spinner when no user is found;
> fix(hovercard): Safeguard user finds in hovercards

- app/packages/partup-client-admin/Admin.html
- app/packages/partup-client-admin/Admin.js
- app/packages/partup-client-pages/modal/profile_settings/advanced/advanced.html
- app/packages/partup-client-pages/modal/profile_settings/advanced/advanced.js
- app/packages/partup-lib/collections/impersonationrequests.js
- app/packages/partup-lib/helpers/impersonation.js
- app/packages/partup-lib/helpers/impersonation.test.js
- app/packages/partup-lib/package.js
- app/packages/partup-lib/schemas/impersonationrequest.js
- app/packages/partup-server/collection_hooks.js
- app/packages/partup-server/methods/users/users_methods.js
In order to comply for `Impersonation in advance profile settings should only show after request by admin` in #1684 the following changes have been made to the impersonation flow:
1. An impersonation request is no longer stored in the key `impersonation` on the `user` object, a new entity called `ImpersonationRequest` is created instead;
1. A request stays valid for 30 minutes, the user must accept before this time or the admin must create a new request;
1. The admin must also start the impersonation within these 30 minutes;
1. An impersonation stays active for 30 minutes starting from the moment the admin starts the impersonation;
1. The admin can impersonate multiple times within the allowed time period;
1. The flow is non-reactive so the admin & user need to refresh after actions.
> feat(impersonation): Improve impersonation flow

- app/packages/partup-client-boardview/BoardView.js
- app/packages/partup-server/methods/activities/activities_methods.js
Test case:
- Create 3 activities in a part-up
- 1 normal, 1 archived and 1 deleted;
- Create a new Part-up and copy the activities from the partup above;
- Create a new activity while in the part-up creation screen and delete it;
- Finish the creation of the part-up and navigate to the board;
- Create a new activity and delete it.
No archived or deleted activities should be visible.
Closes: #1699
> fix(activities): no longer copy archived and deleted activities
